electrode_meta_data = struct(...
    'x', '1',...
    'y', '2',...
    'z', '2',...
    'imp', '1.3',... #impedance
    'filtering','Filtered with a highpass',...
    'id', '1',...  #must be int
    'location','hippocampus'...
    );
    
electrode_group = struct(...
    'device','Spike2',...
    'electrode_name','neuropixel tetrode',...
    'description', 'catalog item #',...
    'location','hippocampus recording'...
    );

