imaging_plane = struct(...
'name', 'my plane',...
'description', 'Session with lots of axons',...
'device', 'Bergamo 2P',...
'excitation_lambda', '500',...
'imaging_rate', '200',...
'indicator', 'GCaMP',...
'location', 'cortex',...
'manifold', '1000, 1000',...
'conversion', '3',...
'unit','Meters',...
'reference_frame','start with the first image'... #Describes position and reference frame of manifold based on position of first element in manifold'
);

two_photon_series = struct(...
'name', 'My 2 photon series',...
'description', 'Session with lots of axons',...
'unit', 'nm',...
'dimension', '1000, 1000, 1000',... #Number of pixels on x, y, (and z) axes.
'field_of_view', '1,1,1',... #'width, height, depth in meters. 
'pmt_gain', '12',...
'scan_line_rate', '3',...
'starting_frame', '1',...
'bits_per_pixel', '32',...
'resolution', '1',... #nm
'conversion', '10',... #pixels per nm
'session_start_time', '2019-05-30 13:34:24.182743-07:00',...
'timestamps_reference_time','1890-05-30 13:34:24.182743-07:00',...# date and time corresponding to time zero of all timestamps; defaults to value of session_start_time
'rate', '100',...#hz
'comments', 'I love axons',...
'control_description', 'whiskey, tango, foxtrot',...#[List]description of each control value
'control', '1,2,3',... #Numerical labels that apply to each element in data
'starting_time', '12'...
);

optical_channel = struct(...
'name','Oregon Green',...
'description', 'The green channel',...
'emission_lambda', '500'...
);

processing_module = struct(...
'name', 'My image processing module',...
'description', 'This holds image, pixel, voxel masks, dF/F and/or Fluorescence'...
);

plane_segmentation = struct(...
'name', 'My plane segmentation',...   
'description','This holds the imaging plane',...
'ID','1'... 
);

roi_response_series = struct(...
'name', 'My ROI response series',...
'unit','Meters',...
'resolution','0.5',...
'conversion','2',...
'starting_time','0.0',...
'rate','150',...
'comments', 'When using these ROI, keep in mind...',...
'description','These ROIs are for glowing axons',...
'control_description', 'whiskey, tango, foxtrot',...#[List]description of each control value
'control', '1,2,3'... #Numerical labels that apply to each element in data
);

    