# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2PhotonStep1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1147, 668)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1111, 800))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(450, 20, 20, 551))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 100, 361, 271))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.column_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.column_1.setContentsMargins(0, 0, 0, 0)
        self.column_1.setObjectName("column_1")
        self.description_le2 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.description_le2.setObjectName("description_le2")
        self.column_1.addWidget(self.description_le2, 1, 1, 1, 1)
        self.emission_lambda_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.emission_lambda_lbl.setObjectName("emission_lambda_lbl")
        self.column_1.addWidget(self.emission_lambda_lbl, 2, 0, 1, 1)
        self.description_lbl2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.description_lbl2.setObjectName("description_lbl2")
        self.column_1.addWidget(self.description_lbl2, 1, 0, 1, 1)
        self.name_le2 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.name_le2.setObjectName("name_le2")
        self.column_1.addWidget(self.name_le2, 0, 1, 1, 1)
        self.emission_lambda_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.emission_lambda_le.setObjectName("emission_lambda_le")
        self.column_1.addWidget(self.emission_lambda_le, 2, 1, 1, 1)
        self.name_lbl2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.name_lbl2.setObjectName("name_lbl2")
        self.column_1.addWidget(self.name_lbl2, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(590, 120, 441, 461))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.column_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.column_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.column_2.setContentsMargins(0, 0, 0, 0)
        self.column_2.setObjectName("column_2")
        self.location_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.location_lbl.setObjectName("location_lbl")
        self.column_2.addWidget(self.location_lbl, 9, 0, 1, 1)
        self.location_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.location_le.setObjectName("location_le")
        self.column_2.addWidget(self.location_le, 9, 1, 1, 1)
        self.indicator_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.indicator_lbl.setObjectName("indicator_lbl")
        self.column_2.addWidget(self.indicator_lbl, 6, 0, 1, 1)
        self.unit_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.unit_le.setObjectName("unit_le")
        self.column_2.addWidget(self.unit_le, 7, 1, 1, 1)
        self.unit_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.unit_lbl.setObjectName("unit_lbl")
        self.column_2.addWidget(self.unit_lbl, 7, 0, 1, 1)
        self.reference_frame_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.reference_frame_lbl.setObjectName("reference_frame_lbl")
        self.column_2.addWidget(self.reference_frame_lbl, 8, 0, 1, 1)
        self.device_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.device_le.setObjectName("device_le")
        self.column_2.addWidget(self.device_le, 2, 1, 1, 1)
        self.conversion_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.conversion_le.setObjectName("conversion_le")
        self.column_2.addWidget(self.conversion_le, 5, 1, 1, 1)
        self.reference_frame_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.reference_frame_le.setObjectName("reference_frame_le")
        self.column_2.addWidget(self.reference_frame_le, 8, 1, 1, 1)
        self.conversion_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.conversion_lbl.setObjectName("conversion_lbl")
        self.column_2.addWidget(self.conversion_lbl, 5, 0, 1, 1)
        self.indicator_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.indicator_le.setObjectName("indicator_le")
        self.column_2.addWidget(self.indicator_le, 6, 1, 1, 1)
        self.imaging_rate_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.imaging_rate_le.setObjectName("imaging_rate_le")
        self.column_2.addWidget(self.imaging_rate_le, 4, 1, 1, 1)
        self.excitation_lambda_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.excitation_lambda_lbl.setObjectName("excitation_lambda_lbl")
        self.column_2.addWidget(self.excitation_lambda_lbl, 3, 0, 1, 1)
        self.name_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.name_lbl.setObjectName("name_lbl")
        self.column_2.addWidget(self.name_lbl, 0, 0, 1, 1)
        self.device_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.device_lbl.setObjectName("device_lbl")
        self.column_2.addWidget(self.device_lbl, 2, 0, 1, 1)
        self.excitation_lambda_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.excitation_lambda_le.setObjectName("excitation_lambda_le")
        self.column_2.addWidget(self.excitation_lambda_le, 3, 1, 1, 1)
        self.description_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.description_le.setObjectName("description_le")
        self.column_2.addWidget(self.description_le, 1, 1, 1, 1)
        self.description_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.description_lbl.setObjectName("description_lbl")
        self.column_2.addWidget(self.description_lbl, 1, 0, 1, 1)
        self.imaging_rate_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.imaging_rate_lbl.setObjectName("imaging_rate_lbl")
        self.column_2.addWidget(self.imaging_rate_lbl, 4, 0, 1, 1)
        self.name_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.name_le.setObjectName("name_le")
        self.column_2.addWidget(self.name_le, 0, 1, 1, 1)
        self.update_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.update_btn.setObjectName("update_btn")
        self.column_2.addWidget(self.update_btn, 11, 1, 1, 1)
        self.manifold_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.manifold_le.setObjectName("manifold_le")
        self.column_2.addWidget(self.manifold_le, 10, 1, 1, 1)
        self.manifold_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.manifold_lbl.setObjectName("manifold_lbl")
        self.column_2.addWidget(self.manifold_lbl, 10, 0, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 302, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.optical_channe_lbl_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.optical_channe_lbl_grid.setContentsMargins(0, 0, 0, 0)
        self.optical_channe_lbl_grid.setObjectName("optical_channe_lbl_grid")
        self.optical_channel_lbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.optical_channel_lbl.setEnabled(False)
        self.optical_channel_lbl.setMinimumSize(QtCore.QSize(300, 0))
        self.optical_channel_lbl.setMaximumSize(QtCore.QSize(16777211, 189))
        self.optical_channel_lbl.setObjectName("optical_channel_lbl")
        self.optical_channe_lbl_grid.addWidget(self.optical_channel_lbl, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(590, 20, 441, 80))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.imaging_plane_lbl_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.imaging_plane_lbl_grid.setContentsMargins(0, 0, 0, 0)
        self.imaging_plane_lbl_grid.setObjectName("imaging_plane_lbl_grid")
        self.optical_channel_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.optical_channel_lbl_2.setEnabled(False)
        self.optical_channel_lbl_2.setMaximumSize(QtCore.QSize(16777215, 189))
        self.optical_channel_lbl_2.setObjectName("optical_channel_lbl_2")
        self.imaging_plane_lbl_grid.addWidget(self.optical_channel_lbl_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.emission_lambda_lbl.setText(_translate("Dialog", "Emission Lamda"))
        self.description_lbl2.setText(_translate("Dialog", "Description"))
        self.name_lbl2.setText(_translate("Dialog", "Name"))
        self.location_lbl.setText(_translate("Dialog", "Location"))
        self.indicator_lbl.setText(_translate("Dialog", "Indicator"))
        self.unit_lbl.setText(_translate("Dialog", "Unit"))
        self.reference_frame_lbl.setText(_translate("Dialog", "Reference Frame"))
        self.conversion_lbl.setText(_translate("Dialog", "Conversion"))
        self.excitation_lambda_lbl.setText(_translate("Dialog", "Excitation Lamda"))
        self.name_lbl.setText(_translate("Dialog", "Name"))
        self.device_lbl.setText(_translate("Dialog", "Device"))
        self.description_lbl.setText(_translate("Dialog", "Description"))
        self.imaging_rate_lbl.setText(_translate("Dialog", "Imaging Rate"))
        self.update_btn.setText(_translate("Dialog", "Update/Verify"))
        self.manifold_lbl.setText(_translate("Dialog", "Manifold"))
        self.optical_channel_lbl.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Optical Channel</span></p></body></html>"))
        self.optical_channel_lbl_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Imaging Plane</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

