# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2PhotonStep2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1523, 916)
        self.left_Frame = QtWidgets.QFrame(Dialog)
        self.left_Frame.setGeometry(QtCore.QRect(20, 10, 721, 900))
        self.left_Frame.setMinimumSize(QtCore.QSize(0, 900))
        self.left_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_Frame.setObjectName("left_Frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.left_Frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 341, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.two_photon_series_grid_1 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.two_photon_series_grid_1.setContentsMargins(0, 0, 0, 0)
        self.two_photon_series_grid_1.setObjectName("two_photon_series_grid_1")
        self.two_photon_series_lbl = QtWidgets.QLabel(self.gridLayoutWidget)
        self.two_photon_series_lbl.setObjectName("two_photon_series_lbl")
        self.two_photon_series_grid_1.addWidget(self.two_photon_series_lbl, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.left_Frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 671, 651))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.two_photon_series_part1_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.two_photon_series_part1_grid.setContentsMargins(0, 0, 0, 0)
        self.two_photon_series_part1_grid.setObjectName("two_photon_series_part1_grid")
        self.bits_per_pixel_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.bits_per_pixel_le.setObjectName("bits_per_pixel_le")
        self.two_photon_series_part1_grid.addWidget(self.bits_per_pixel_le, 5, 1, 1, 1)
        self.unit_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.unit_lbl.setObjectName("unit_lbl")
        self.two_photon_series_part1_grid.addWidget(self.unit_lbl, 3, 0, 1, 1)
        self.bits_per_pixel_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.bits_per_pixel_lbl.setObjectName("bits_per_pixel_lbl")
        self.two_photon_series_part1_grid.addWidget(self.bits_per_pixel_lbl, 5, 0, 1, 1)
        self.field_of_view_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.field_of_view_lbl.setObjectName("field_of_view_lbl")
        self.two_photon_series_part1_grid.addWidget(self.field_of_view_lbl, 4, 0, 1, 1)
        self.dimension_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.dimension_lbl.setObjectName("dimension_lbl")
        self.two_photon_series_part1_grid.addWidget(self.dimension_lbl, 7, 0, 1, 1)
        self.pmt_gain_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.pmt_gain_lbl.setObjectName("pmt_gain_lbl")
        self.two_photon_series_part1_grid.addWidget(self.pmt_gain_lbl, 6, 0, 1, 1)
        self.comments_pte = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.comments_pte.setMaximumSize(QtCore.QSize(16777215, 170))
        self.comments_pte.setObjectName("comments_pte")
        self.two_photon_series_part1_grid.addWidget(self.comments_pte, 2, 1, 1, 1)
        self.comments_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.comments_lbl.setObjectName("comments_lbl")
        self.two_photon_series_part1_grid.addWidget(self.comments_lbl, 2, 0, 1, 1)
        self.name_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.name_lbl.setObjectName("name_lbl")
        self.two_photon_series_part1_grid.addWidget(self.name_lbl, 0, 0, 1, 1)
        self.name_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.name_le.setObjectName("name_le")
        self.two_photon_series_part1_grid.addWidget(self.name_le, 0, 1, 1, 1)
        self.field_of_view_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.field_of_view_le.setObjectName("field_of_view_le")
        self.two_photon_series_part1_grid.addWidget(self.field_of_view_le, 4, 1, 1, 1)
        self.description_pte = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.description_pte.setMaximumSize(QtCore.QSize(16777215, 146))
        self.description_pte.setObjectName("description_pte")
        self.two_photon_series_part1_grid.addWidget(self.description_pte, 1, 1, 1, 1)
        self.unit_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.unit_le.setObjectName("unit_le")
        self.two_photon_series_part1_grid.addWidget(self.unit_le, 3, 1, 1, 1)
        self.description_le = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.description_le.setObjectName("description_le")
        self.two_photon_series_part1_grid.addWidget(self.description_le, 1, 0, 1, 1)
        self.pmt_gain_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.pmt_gain_le.setObjectName("pmt_gain_le")
        self.two_photon_series_part1_grid.addWidget(self.pmt_gain_le, 6, 1, 1, 1)
        self.dimension_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.dimension_le.setObjectName("dimension_le")
        self.two_photon_series_part1_grid.addWidget(self.dimension_le, 7, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(850, 30, 1200, 900))
        self.frame_2.setMinimumSize(QtCore.QSize(1200, 900))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 60, 491, 451))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.two_photon_part2_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.two_photon_part2_grid.setContentsMargins(0, 0, 0, 0)
        self.two_photon_part2_grid.setObjectName("two_photon_part2_grid")
        self.starting_frame_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.starting_frame_le.setObjectName("starting_frame_le")
        self.two_photon_part2_grid.addWidget(self.starting_frame_le, 3, 1, 1, 1)
        self.conversion_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.conversion_le.setObjectName("conversion_le")
        self.two_photon_part2_grid.addWidget(self.conversion_le, 1, 1, 1, 1)
        self.starting_time_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.starting_time_le.setObjectName("starting_time_le")
        self.two_photon_part2_grid.addWidget(self.starting_time_le, 2, 1, 1, 1)
        self.rate_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.rate_le.setObjectName("rate_le")
        self.two_photon_part2_grid.addWidget(self.rate_le, 4, 1, 1, 1)
        self.conversion_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.conversion_lbl.setObjectName("conversion_lbl")
        self.two_photon_part2_grid.addWidget(self.conversion_lbl, 1, 0, 1, 1)
        self.control_description_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.control_description_le.setObjectName("control_description_le")
        self.two_photon_part2_grid.addWidget(self.control_description_le, 7, 1, 1, 1)
        self.scan_line_rate_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.scan_line_rate_le.setObjectName("scan_line_rate_le")
        self.two_photon_part2_grid.addWidget(self.scan_line_rate_le, 5, 1, 1, 1)
        self.control_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.control_le.setObjectName("control_le")
        self.two_photon_part2_grid.addWidget(self.control_le, 6, 1, 1, 1)
        self.rate_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.rate_lbl.setObjectName("rate_lbl")
        self.two_photon_part2_grid.addWidget(self.rate_lbl, 4, 0, 1, 1)
        self.scan_line_rate = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.scan_line_rate.setObjectName("scan_line_rate")
        self.two_photon_part2_grid.addWidget(self.scan_line_rate, 5, 0, 1, 1)
        self.starting_time_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.starting_time_lbl.setObjectName("starting_time_lbl")
        self.two_photon_part2_grid.addWidget(self.starting_time_lbl, 2, 0, 1, 1)
        self.control_description_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.control_description_lbl.setObjectName("control_description_lbl")
        self.two_photon_part2_grid.addWidget(self.control_description_lbl, 7, 0, 1, 1)
        self.resolution_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.resolution_le.setObjectName("resolution_le")
        self.two_photon_part2_grid.addWidget(self.resolution_le, 0, 1, 1, 1)
        self.resolution_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.resolution_lbl.setObjectName("resolution_lbl")
        self.two_photon_part2_grid.addWidget(self.resolution_lbl, 0, 0, 1, 1)
        self.control_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.control_lbl.setObjectName("control_lbl")
        self.two_photon_part2_grid.addWidget(self.control_lbl, 6, 0, 1, 1)
        self.starting_frame_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.starting_frame_lbl.setObjectName("starting_frame_lbl")
        self.two_photon_part2_grid.addWidget(self.starting_frame_lbl, 3, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 520, 251, 51))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.objects_in_file_grid_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.objects_in_file_grid_2.setContentsMargins(0, 0, 0, 0)
        self.objects_in_file_grid_2.setObjectName("objects_in_file_grid_2")
        self.objects_in_file_lbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.objects_in_file_lbl.setObjectName("objects_in_file_lbl")
        self.objects_in_file_grid_2.addWidget(self.objects_in_file_lbl, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 441, 41))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.two_photon_series_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.two_photon_series_grid.setContentsMargins(0, 0, 0, 0)
        self.two_photon_series_grid.setObjectName("two_photon_series_grid")
        self.two_photon_series2_grid = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.two_photon_series2_grid.setObjectName("two_photon_series2_grid")
        self.two_photon_series_grid.addWidget(self.two_photon_series2_grid, 0, 0, 1, 1)
        self.update_btn = QtWidgets.QPushButton(self.frame_2)
        self.update_btn.setGeometry(QtCore.QRect(10, 700, 150, 30))
        self.update_btn.setMinimumSize(QtCore.QSize(150, 30))
        self.update_btn.setObjectName("update_btn")
        self.save_btn = QtWidgets.QPushButton(self.frame_2)
        self.save_btn.setGeometry(QtCore.QRect(310, 700, 150, 30))
        self.save_btn.setMinimumSize(QtCore.QSize(150, 30))
        self.save_btn.setObjectName("save_btn")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 590, 521, 81))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.objects_in_file_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.objects_in_file_grid.setContentsMargins(0, 0, 0, 0)
        self.objects_in_file_grid.setObjectName("objects_in_file_grid")
        self.path_to_image_stack_lbl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.path_to_image_stack_lbl.setObjectName("path_to_image_stack_lbl")
        self.objects_in_file_grid.addWidget(self.path_to_image_stack_lbl, 1, 0, 1, 1)
        self.path_to_stack_updates_lbl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.path_to_stack_updates_lbl.setObjectName("path_to_stack_updates_lbl")
        self.objects_in_file_grid.addWidget(self.path_to_stack_updates_lbl, 1, 1, 1, 1)
        self.imaging_plane_updates_lbl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.imaging_plane_updates_lbl.setObjectName("imaging_plane_updates_lbl")
        self.objects_in_file_grid.addWidget(self.imaging_plane_updates_lbl, 0, 1, 1, 1)
        self.imaging_plane_lbl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.imaging_plane_lbl.setObjectName("imaging_plane_lbl")
        self.objects_in_file_grid.addWidget(self.imaging_plane_lbl, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.two_photon_series_lbl.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Two Photon Series</span></p></body></html>"))
        self.unit_lbl.setText(_translate("Dialog", "Unit"))
        self.bits_per_pixel_lbl.setText(_translate("Dialog", "Bits Per Pixel"))
        self.field_of_view_lbl.setText(_translate("Dialog", "Field of View"))
        self.dimension_lbl.setText(_translate("Dialog", "Dimension"))
        self.pmt_gain_lbl.setText(_translate("Dialog", "PhotoMultiplier Gain"))
        self.comments_lbl.setText(_translate("Dialog", "Comments"))
        self.name_lbl.setText(_translate("Dialog", "Name"))
        self.description_le.setText(_translate("Dialog", "Description"))
        self.conversion_lbl.setText(_translate("Dialog", "Conversion"))
        self.rate_lbl.setText(_translate("Dialog", "Rate"))
        self.scan_line_rate.setText(_translate("Dialog", "Scan Line Rate"))
        self.starting_time_lbl.setText(_translate("Dialog", "Starting Time"))
        self.control_description_lbl.setText(_translate("Dialog", "Control Description"))
        self.resolution_lbl.setText(_translate("Dialog", "Resolution"))
        self.control_lbl.setText(_translate("Dialog", "Control"))
        self.starting_frame_lbl.setText(_translate("Dialog", "Starting Frame"))
        self.objects_in_file_lbl.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Objects in File</span></p></body></html>"))
        self.two_photon_series2_grid.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Two Photon Series</span></p></body></html>"))
        self.update_btn.setText(_translate("Dialog", "Update/Verify"))
        self.save_btn.setText(_translate("Dialog", "Save"))
        self.path_to_image_stack_lbl.setText(_translate("Dialog", "Path to Image Stack:"))
        self.path_to_stack_updates_lbl.setText(_translate("Dialog", "path_to_stack_updates"))
        self.imaging_plane_updates_lbl.setText(_translate("Dialog", "imaging_plane_updates"))
        self.imaging_plane_lbl.setText(_translate("Dialog", "Imaging Plane:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

