# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EphysStep2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(982, 865)
        self.add_electrode_group_gb = QtWidgets.QGroupBox(Dialog)
        self.add_electrode_group_gb.setGeometry(QtCore.QRect(20, 60, 471, 291))
        self.add_electrode_group_gb.setObjectName("add_electrode_group_gb")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.add_electrode_group_gb)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 19, 441, 261))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.add_electrode_group_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.add_electrode_group_grid.setContentsMargins(0, 0, 0, 0)
        self.add_electrode_group_grid.setObjectName("add_electrode_group_grid")
        self.location_le = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.location_le.setObjectName("location_le")
        self.add_electrode_group_grid.addWidget(self.location_le, 3, 1, 1, 1)
        self.electrode_name_lbl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.electrode_name_lbl.setObjectName("electrode_name_lbl")
        self.add_electrode_group_grid.addWidget(self.electrode_name_lbl, 1, 0, 1, 1)
        self.description_lbl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.description_lbl.setObjectName("description_lbl")
        self.add_electrode_group_grid.addWidget(self.description_lbl, 2, 0, 1, 1)
        self.description_le = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.description_le.setObjectName("description_le")
        self.add_electrode_group_grid.addWidget(self.description_le, 2, 1, 1, 1)
        self.location_lbl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.location_lbl.setObjectName("location_lbl")
        self.add_electrode_group_grid.addWidget(self.location_lbl, 3, 0, 1, 1)
        self.electrode_name_le = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.electrode_name_le.setObjectName("electrode_name_le")
        self.add_electrode_group_grid.addWidget(self.electrode_name_le, 1, 1, 1, 1)
        self.device_le = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.device_le.setObjectName("device_le")
        self.add_electrode_group_grid.addWidget(self.device_le, 0, 1, 1, 1)
        self.device_lbl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.device_lbl.setObjectName("device_lbl")
        self.add_electrode_group_grid.addWidget(self.device_lbl, 0, 0, 1, 1)
        self.add_electrode_gb = QtWidgets.QGroupBox(Dialog)
        self.add_electrode_gb.setGeometry(QtCore.QRect(20, 360, 471, 451))
        self.add_electrode_gb.setObjectName("add_electrode_gb")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.add_electrode_gb)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(60, 340, 101, 80))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.x_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.x_grid.setContentsMargins(0, 0, 0, 0)
        self.x_grid.setObjectName("x_grid")
        self.x_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.x_le.setObjectName("x_le")
        self.x_grid.addWidget(self.x_le, 0, 1, 1, 1)
        self.x_lbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.x_lbl.setObjectName("x_lbl")
        self.x_grid.addWidget(self.x_lbl, 0, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.add_electrode_gb)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(160, 340, 101, 80))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.y_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.y_grid.setContentsMargins(0, 0, 0, 0)
        self.y_grid.setObjectName("y_grid")
        self.y_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.y_le.setObjectName("y_le")
        self.y_grid.addWidget(self.y_le, 0, 1, 1, 1)
        self.y_lbl = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.y_lbl.setObjectName("y_lbl")
        self.y_grid.addWidget(self.y_lbl, 0, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.add_electrode_gb)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(270, 340, 101, 80))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.z_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.z_grid.setContentsMargins(0, 0, 0, 0)
        self.z_grid.setObjectName("z_grid")
        self.z_le = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.z_le.setObjectName("z_le")
        self.z_grid.addWidget(self.z_le, 0, 1, 1, 1)
        self.z_lbl = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.z_lbl.setObjectName("z_lbl")
        self.z_grid.addWidget(self.z_lbl, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.add_electrode_gb)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 441, 261))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.add_electrode_grid = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.add_electrode_grid.setContentsMargins(0, 0, 0, 0)
        self.add_electrode_grid.setObjectName("add_electrode_grid")
        self.filtering_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.filtering_le.setObjectName("filtering_le")
        self.add_electrode_grid.addWidget(self.filtering_le, 1, 1, 1, 1)
        self.id_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.id_le.setObjectName("id_le")
        self.add_electrode_grid.addWidget(self.id_le, 0, 1, 1, 1)
        self.filtering_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.filtering_lbl.setObjectName("filtering_lbl")
        self.add_electrode_grid.addWidget(self.filtering_lbl, 1, 0, 1, 1)
        self.id_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.id_lbl.setObjectName("id_lbl")
        self.add_electrode_grid.addWidget(self.id_lbl, 0, 0, 1, 1)
        self.location_le_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.location_le_2.setObjectName("location_le_2")
        self.add_electrode_grid.addWidget(self.location_le_2, 2, 1, 1, 1)
        self.location_lbl_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.location_lbl_2.setObjectName("location_lbl_2")
        self.add_electrode_grid.addWidget(self.location_lbl_2, 2, 0, 1, 1)
        self.imp_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.imp_le.setObjectName("imp_le")
        self.add_electrode_grid.addWidget(self.imp_le, 3, 1, 1, 1)
        self.imp_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.imp_lbl.setObjectName("imp_lbl")
        self.add_electrode_grid.addWidget(self.imp_lbl, 3, 0, 1, 1)
        self.electrode_table = QtWidgets.QTableWidget(Dialog)
        self.electrode_table.setGeometry(QtCore.QRect(520, 70, 441, 51))
        self.electrode_table.setObjectName("electrode_table")
        self.electrode_table.setColumnCount(2)
        self.electrode_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.electrode_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.electrode_table.setHorizontalHeaderItem(1, item)
        self.update_btn = QtWidgets.QPushButton(Dialog)
        self.update_btn.setGeometry(QtCore.QRect(780, 630, 161, 31))
        self.update_btn.setObjectName("update_btn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 471, 51))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.add_electrode_group_gb.setTitle(_translate("Dialog", "Add Electrode Group"))
        self.electrode_name_lbl.setText(_translate("Dialog", "Electrode Name"))
        self.description_lbl.setText(_translate("Dialog", "Description"))
        self.location_lbl.setText(_translate("Dialog", "Location"))
        self.device_lbl.setText(_translate("Dialog", "Device"))
        self.add_electrode_gb.setTitle(_translate("Dialog", "Add Electrode"))
        self.x_lbl.setText(_translate("Dialog", "    x "))
        self.y_lbl.setText(_translate("Dialog", "    y "))
        self.z_lbl.setText(_translate("Dialog", "   z "))
        self.filtering_lbl.setText(_translate("Dialog", "Filtering"))
        self.id_lbl.setText(_translate("Dialog", "ID "))
        self.location_lbl_2.setText(_translate("Dialog", "Location"))
        self.imp_lbl.setText(_translate("Dialog", "Impedance"))
        item = self.electrode_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Region"))
        item = self.electrode_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Description"))
        self.update_btn.setText(_translate("Dialog", "Update/Verify"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">Add electrode meta data</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

