# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HeaderScreen.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1452, 635)
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setSizeIncrement(QtCore.QSize(1, 4))
        Dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Dialog.setToolTipDuration(0)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1401, 821))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(370, 10, 16, 551))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 15, 341, 541))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.column_1 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.column_1.setContentsMargins(0, 0, 0, 0)
        self.column_1.setObjectName("column_1")
        self.keywords_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.keywords_le.setObjectName("keywords_le")
        self.column_1.addWidget(self.keywords_le, 3, 1, 1, 1)
        self.experimenter_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.experimenter_lbl.setObjectName("experimenter_lbl")
        self.column_1.addWidget(self.experimenter_lbl, 0, 0, 1, 1)
        self.relatedpublications_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.relatedpublications_le.setObjectName("relatedpublications_le")
        self.column_1.addWidget(self.relatedpublications_le, 5, 1, 1, 1)
        self.protocol_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.protocol_le.setObjectName("protocol_le")
        self.column_1.addWidget(self.protocol_le, 4, 1, 1, 1)
        self.institution_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.institution_le.setObjectName("institution_le")
        self.column_1.addWidget(self.institution_le, 1, 1, 1, 1)
        self.experimenter_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.experimenter_le.setObjectName("experimenter_le")
        self.column_1.addWidget(self.experimenter_le, 0, 1, 1, 1)
        self.protocol_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.protocol_lbl.setObjectName("protocol_lbl")
        self.column_1.addWidget(self.protocol_lbl, 4, 0, 1, 1)
        self.institution_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.institution_lbl.setObjectName("institution_lbl")
        self.column_1.addWidget(self.institution_lbl, 1, 0, 1, 1)
        self.lab_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.lab_lbl.setObjectName("lab_lbl")
        self.column_1.addWidget(self.lab_lbl, 2, 0, 1, 1)
        self.related_publications_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.related_publications_lbl.setObjectName("related_publications_lbl")
        self.column_1.addWidget(self.related_publications_lbl, 5, 0, 1, 1)
        self.keywords_lbl = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.keywords_lbl.setObjectName("keywords_lbl")
        self.column_1.addWidget(self.keywords_lbl, 3, 0, 1, 1)
        self.lable_le = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lable_le.setObjectName("lable_le")
        self.column_1.addWidget(self.lable_le, 2, 1, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(400, 10, 401, 541))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.column_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.column_2.setContentsMargins(0, 0, 0, 0)
        self.column_2.setObjectName("column_2")
        self.notes_pte = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.notes_pte.setObjectName("notes_pte")
        self.column_2.addWidget(self.notes_pte, 0, 1, 1, 1)
        self.notes_lbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.notes_lbl.setObjectName("notes_lbl")
        self.column_2.addWidget(self.notes_lbl, 0, 0, 1, 1)
        self.experiment_description_lbl = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.experiment_description_lbl.setObjectName("experiment_description_lbl")
        self.column_2.addWidget(self.experiment_description_lbl, 1, 0, 1, 1)
        self.experiment_description_pte = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_5)
        self.experiment_description_pte.setObjectName("experiment_description_pte")
        self.column_2.addWidget(self.experiment_description_pte, 1, 1, 1, 1)
        self.line_1 = QtWidgets.QFrame(self.frame)
        self.line_1.setGeometry(QtCore.QRect(810, 10, 16, 541))
        self.line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(820, 10, 571, 521))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.column_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.column_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.column_3.setContentsMargins(0, 0, 0, 0)
        self.column_3.setObjectName("column_3")
        self.session_id_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.session_id_lbl.setObjectName("session_id_lbl")
        self.column_3.addWidget(self.session_id_lbl, 0, 0, 1, 1)
        self.pharmacology_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.pharmacology_lbl.setObjectName("pharmacology_lbl")
        self.column_3.addWidget(self.pharmacology_lbl, 4, 0, 1, 1)
        self.timestamps_reference_time_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.timestamps_reference_time_lbl.setObjectName("timestamps_reference_time_lbl")
        self.column_3.addWidget(self.timestamps_reference_time_lbl, 1, 0, 1, 1)
        self.surgery_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.surgery_lbl.setObjectName("surgery_lbl")
        self.column_3.addWidget(self.surgery_lbl, 2, 0, 1, 1)
        self.session_id_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.session_id_le.setObjectName("session_id_le")
        self.column_3.addWidget(self.session_id_le, 0, 1, 1, 1)
        self.surgery_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.surgery_le.setObjectName("surgery_le")
        self.column_3.addWidget(self.surgery_le, 2, 1, 1, 1)
        self.virus_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.virus_le.setObjectName("virus_le")
        self.column_3.addWidget(self.virus_le, 3, 1, 1, 1)
        self.pharmacology_le = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.pharmacology_le.setObjectName("pharmacology_le")
        self.column_3.addWidget(self.pharmacology_le, 4, 1, 1, 1)
        self.virus_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.virus_lbl.setObjectName("virus_lbl")
        self.column_3.addWidget(self.virus_lbl, 3, 0, 1, 1)
        self.timestamps_reference_time_dte = QtWidgets.QDateTimeEdit(self.gridLayoutWidget_2)
        self.timestamps_reference_time_dte.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.timestamps_reference_time_dte.setTimeSpec(QtCore.Qt.TimeZone)
        self.timestamps_reference_time_dte.setObjectName("timestamps_reference_time_dte")
        self.column_3.addWidget(self.timestamps_reference_time_dte, 1, 1, 1, 1)
        self.session_description_pte = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.session_description_pte.setObjectName("session_description_pte")
        self.column_3.addWidget(self.session_description_pte, 6, 1, 1, 1)
        self.session_start_time_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.session_start_time_lbl.setObjectName("session_start_time_lbl")
        self.column_3.addWidget(self.session_start_time_lbl, 5, 0, 1, 1)
        self.session_start_time_dte = QtWidgets.QDateTimeEdit(self.gridLayoutWidget_2)
        self.session_start_time_dte.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.session_start_time_dte.setTimeSpec(QtCore.Qt.TimeZone)
        self.session_start_time_dte.setObjectName("session_start_time_dte")
        self.column_3.addWidget(self.session_start_time_dte, 5, 1, 1, 1)
        self.session_description_lbl = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.session_description_lbl.setObjectName("session_description_lbl")
        self.column_3.addWidget(self.session_description_lbl, 6, 0, 1, 1)
        self.column_3.setColumnMinimumWidth(0, 200)
        self.column_3.setColumnMinimumWidth(1, 200)
        self.update_btn = QtWidgets.QPushButton(self.frame)
        self.update_btn.setGeometry(QtCore.QRect(1260, 540, 150, 32))
        self.update_btn.setMinimumSize(QtCore.QSize(0, 11))
        self.update_btn.setObjectName("update_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.experimenter_lbl.setText(_translate("Dialog", "Experimenter"))
        self.protocol_lbl.setText(_translate("Dialog", "Protocol"))
        self.institution_lbl.setText(_translate("Dialog", "Institution"))
        self.lab_lbl.setText(_translate("Dialog", "Lab"))
        self.related_publications_lbl.setText(_translate("Dialog", "Related \n"
"publications"))
        self.keywords_lbl.setText(_translate("Dialog", "Keywords"))
        self.notes_lbl.setText(_translate("Dialog", "Notes"))
        self.experiment_description_lbl.setText(_translate("Dialog", "Experiment \n"
"Description"))
        self.session_id_lbl.setText(_translate("Dialog", "Session ID"))
        self.pharmacology_lbl.setText(_translate("Dialog", "Pharmacology"))
        self.timestamps_reference_time_lbl.setText(_translate("Dialog", "Timestamps Reference Time"))
        self.surgery_lbl.setText(_translate("Dialog", "Surgery"))
        self.virus_lbl.setText(_translate("Dialog", "Virus"))
        self.timestamps_reference_time_dte.setDisplayFormat(_translate("Dialog", "yyyy/MM/dd h:mm AP"))
        self.session_start_time_lbl.setText(_translate("Dialog", "Session Start Time"))
        self.session_start_time_dte.setDisplayFormat(_translate("Dialog", "yyyy/MM/dd h:mm AP"))
        self.session_description_lbl.setText(_translate("Dialog", "Session\n"
"Description"))
        self.update_btn.setText(_translate("Dialog", "Update/Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

