# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testinglistview.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1475, 1400)
        Dialog.setMinimumSize(QtCore.QSize(0, 1400))
        self.time_series_translator_gb = QtWidgets.QGroupBox(Dialog)
        self.time_series_translator_gb.setGeometry(QtCore.QRect(60, 20, 981, 1411))
        self.time_series_translator_gb.setMinimumSize(QtCore.QSize(0, 1400))
        self.time_series_translator_gb.setObjectName("time_series_translator_gb")
        self.gridLayoutWidget = QtWidgets.QWidget(self.time_series_translator_gb)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 881, 1221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.time_series_translator_grid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.time_series_translator_grid.setContentsMargins(0, 0, 0, 0)
        self.time_series_translator_grid.setObjectName("time_series_translator_grid")
        self.overwrite_line_cb_14 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_14.setObjectName("overwrite_line_cb_14")
        self.overwrite_line_cb_14.addItem("")
        self.overwrite_line_cb_14.addItem("")
        self.overwrite_line_cb_14.addItem("")
        self.overwrite_line_cb_14.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_14, 13, 1, 1, 1)
        self.overwrite_line_cb_18 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_18.setObjectName("overwrite_line_cb_18")
        self.overwrite_line_cb_18.addItem("")
        self.overwrite_line_cb_18.addItem("")
        self.overwrite_line_cb_18.addItem("")
        self.overwrite_line_cb_18.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_18, 17, 1, 1, 1)
        self.overwrite_line_cb_17 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_17.setObjectName("overwrite_line_cb_17")
        self.overwrite_line_cb_17.addItem("")
        self.overwrite_line_cb_17.addItem("")
        self.overwrite_line_cb_17.addItem("")
        self.overwrite_line_cb_17.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_17, 16, 1, 1, 1)
        self.overwrite_line_cb_15 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_15.setObjectName("overwrite_line_cb_15")
        self.overwrite_line_cb_15.addItem("")
        self.overwrite_line_cb_15.addItem("")
        self.overwrite_line_cb_15.addItem("")
        self.overwrite_line_cb_15.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_15, 14, 1, 1, 1)
        self.overwrite_line_cb_16 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_16.setObjectName("overwrite_line_cb_16")
        self.overwrite_line_cb_16.addItem("")
        self.overwrite_line_cb_16.addItem("")
        self.overwrite_line_cb_16.addItem("")
        self.overwrite_line_cb_16.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_16, 15, 1, 1, 1)
        self.overwrite_line_cb_21 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_21.setObjectName("overwrite_line_cb_21")
        self.overwrite_line_cb_21.addItem("")
        self.overwrite_line_cb_21.addItem("")
        self.overwrite_line_cb_21.addItem("")
        self.overwrite_line_cb_21.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_21, 20, 1, 1, 1)
        self.overwrite_line_cb_19 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_19.setObjectName("overwrite_line_cb_19")
        self.overwrite_line_cb_19.addItem("")
        self.overwrite_line_cb_19.addItem("")
        self.overwrite_line_cb_19.addItem("")
        self.overwrite_line_cb_19.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_19, 18, 1, 1, 1)
        self.overwrite_line_cb_22 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_22.setObjectName("overwrite_line_cb_22")
        self.overwrite_line_cb_22.addItem("")
        self.overwrite_line_cb_22.addItem("")
        self.overwrite_line_cb_22.addItem("")
        self.overwrite_line_cb_22.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_22, 21, 1, 1, 1)
        self.overwrite_line_cb_20 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_20.setObjectName("overwrite_line_cb_20")
        self.overwrite_line_cb_20.addItem("")
        self.overwrite_line_cb_20.addItem("")
        self.overwrite_line_cb_20.addItem("")
        self.overwrite_line_cb_20.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_20, 19, 1, 1, 1)
        self.overwrite_line_cb_10 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_10.setObjectName("overwrite_line_cb_10")
        self.overwrite_line_cb_10.addItem("")
        self.overwrite_line_cb_10.addItem("")
        self.overwrite_line_cb_10.addItem("")
        self.overwrite_line_cb_10.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_10, 9, 1, 1, 1)
        self.overwrite_line_cb_8 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_8.setObjectName("overwrite_line_cb_8")
        self.overwrite_line_cb_8.addItem("")
        self.overwrite_line_cb_8.addItem("")
        self.overwrite_line_cb_8.addItem("")
        self.overwrite_line_cb_8.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_8, 7, 1, 1, 1)
        self.overwrite_line_cb_11 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_11.setObjectName("overwrite_line_cb_11")
        self.overwrite_line_cb_11.addItem("")
        self.overwrite_line_cb_11.addItem("")
        self.overwrite_line_cb_11.addItem("")
        self.overwrite_line_cb_11.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_11, 10, 1, 1, 1)
        self.overwrite_line_cb_9 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_9.setObjectName("overwrite_line_cb_9")
        self.overwrite_line_cb_9.addItem("")
        self.overwrite_line_cb_9.addItem("")
        self.overwrite_line_cb_9.addItem("")
        self.overwrite_line_cb_9.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_9, 8, 1, 1, 1)
        self.overwrite_line_cb_12 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_12.setObjectName("overwrite_line_cb_12")
        self.overwrite_line_cb_12.addItem("")
        self.overwrite_line_cb_12.addItem("")
        self.overwrite_line_cb_12.addItem("")
        self.overwrite_line_cb_12.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_12, 11, 1, 1, 1)
        self.overwrite_line_cb_13 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_13.setObjectName("overwrite_line_cb_13")
        self.overwrite_line_cb_13.addItem("")
        self.overwrite_line_cb_13.addItem("")
        self.overwrite_line_cb_13.addItem("")
        self.overwrite_line_cb_13.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_13, 12, 1, 1, 1)
        self.overwrite_line_cb_24 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_24.setObjectName("overwrite_line_cb_24")
        self.overwrite_line_cb_24.addItem("")
        self.overwrite_line_cb_24.addItem("")
        self.overwrite_line_cb_24.addItem("")
        self.overwrite_line_cb_24.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_24, 23, 1, 1, 1)
        self.overwrite_line_cb_25 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_25.setObjectName("overwrite_line_cb_25")
        self.overwrite_line_cb_25.addItem("")
        self.overwrite_line_cb_25.addItem("")
        self.overwrite_line_cb_25.addItem("")
        self.overwrite_line_cb_25.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_25, 24, 1, 1, 1)
        self.overwrite_line_cb_23 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_23.setObjectName("overwrite_line_cb_23")
        self.overwrite_line_cb_23.addItem("")
        self.overwrite_line_cb_23.addItem("")
        self.overwrite_line_cb_23.addItem("")
        self.overwrite_line_cb_23.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_23, 22, 1, 1, 1)
        self.overwrite_line_cb_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_1.setObjectName("overwrite_line_cb_1")
        self.overwrite_line_cb_1.addItem("")
        self.overwrite_line_cb_1.addItem("")
        self.overwrite_line_cb_1.addItem("")
        self.overwrite_line_cb_1.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_1, 0, 1, 1, 1)
        self.overwrite_line_cb_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_3.setObjectName("overwrite_line_cb_3")
        self.overwrite_line_cb_3.addItem("")
        self.overwrite_line_cb_3.addItem("")
        self.overwrite_line_cb_3.addItem("")
        self.overwrite_line_cb_3.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_3, 2, 1, 1, 1)
        self.overwrite_line_cb_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_2.setObjectName("overwrite_line_cb_2")
        self.overwrite_line_cb_2.addItem("")
        self.overwrite_line_cb_2.addItem("")
        self.overwrite_line_cb_2.addItem("")
        self.overwrite_line_cb_2.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_2, 1, 1, 1, 1)
        self.overwrite_line_cb_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_4.setObjectName("overwrite_line_cb_4")
        self.overwrite_line_cb_4.addItem("")
        self.overwrite_line_cb_4.addItem("")
        self.overwrite_line_cb_4.addItem("")
        self.overwrite_line_cb_4.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_4, 3, 1, 1, 1)
        self.overwrite_line_cb_6 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_6.setObjectName("overwrite_line_cb_6")
        self.overwrite_line_cb_6.addItem("")
        self.overwrite_line_cb_6.addItem("")
        self.overwrite_line_cb_6.addItem("")
        self.overwrite_line_cb_6.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_6, 5, 1, 1, 1)
        self.overwrite_line_cb_5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_5.setObjectName("overwrite_line_cb_5")
        self.overwrite_line_cb_5.addItem("")
        self.overwrite_line_cb_5.addItem("")
        self.overwrite_line_cb_5.addItem("")
        self.overwrite_line_cb_5.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_5, 4, 1, 1, 1)
        self.overwrite_line_cb_7 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.overwrite_line_cb_7.setObjectName("overwrite_line_cb_7")
        self.overwrite_line_cb_7.addItem("")
        self.overwrite_line_cb_7.addItem("")
        self.overwrite_line_cb_7.addItem("")
        self.overwrite_line_cb_7.addItem("")
        self.time_series_translator_grid.addWidget(self.overwrite_line_cb_7, 6, 1, 1, 1)
        self.overwrite_le_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_1.setReadOnly(True)
        self.overwrite_le_1.setObjectName("overwrite_le_1")
        self.time_series_translator_grid.addWidget(self.overwrite_le_1, 0, 0, 1, 1)
        self.overwrite_le_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_2.setReadOnly(True)
        self.overwrite_le_2.setObjectName("overwrite_le_2")
        self.time_series_translator_grid.addWidget(self.overwrite_le_2, 1, 0, 1, 1)
        self.overwrite_le_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_3.setReadOnly(True)
        self.overwrite_le_3.setObjectName("overwrite_le_3")
        self.time_series_translator_grid.addWidget(self.overwrite_le_3, 2, 0, 1, 1)
        self.overwrite_le_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_4.setReadOnly(True)
        self.overwrite_le_4.setObjectName("overwrite_le_4")
        self.time_series_translator_grid.addWidget(self.overwrite_le_4, 3, 0, 1, 1)
        self.overwrite_le_5 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_5.setReadOnly(True)
        self.overwrite_le_5.setObjectName("overwrite_le_5")
        self.time_series_translator_grid.addWidget(self.overwrite_le_5, 4, 0, 1, 1)
        self.overwrite_le_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_6.setReadOnly(True)
        self.overwrite_le_6.setObjectName("overwrite_le_6")
        self.time_series_translator_grid.addWidget(self.overwrite_le_6, 5, 0, 1, 1)
        self.overwrite_le_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_7.setReadOnly(True)
        self.overwrite_le_7.setObjectName("overwrite_le_7")
        self.time_series_translator_grid.addWidget(self.overwrite_le_7, 6, 0, 1, 1)
        self.overwrite_le_8 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_8.setReadOnly(True)
        self.overwrite_le_8.setObjectName("overwrite_le_8")
        self.time_series_translator_grid.addWidget(self.overwrite_le_8, 7, 0, 1, 1)
        self.overwrite_le_9 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_9.setReadOnly(True)
        self.overwrite_le_9.setObjectName("overwrite_le_9")
        self.time_series_translator_grid.addWidget(self.overwrite_le_9, 8, 0, 1, 1)
        self.overwrite_le_10 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_10.setReadOnly(True)
        self.overwrite_le_10.setObjectName("overwrite_le_10")
        self.time_series_translator_grid.addWidget(self.overwrite_le_10, 9, 0, 1, 1)
        self.overwrite_le_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_11.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_11.setReadOnly(True)
        self.overwrite_le_11.setObjectName("overwrite_le_11")
        self.time_series_translator_grid.addWidget(self.overwrite_le_11, 10, 0, 1, 1)
        self.overwrite_le_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_12.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_12.setReadOnly(True)
        self.overwrite_le_12.setObjectName("overwrite_le_12")
        self.time_series_translator_grid.addWidget(self.overwrite_le_12, 11, 0, 1, 1)
        self.overwrite_le_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_13.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_13.setReadOnly(True)
        self.overwrite_le_13.setObjectName("overwrite_le_13")
        self.time_series_translator_grid.addWidget(self.overwrite_le_13, 12, 0, 1, 1)
        self.overwrite_le_14 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_14.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_14.setReadOnly(True)
        self.overwrite_le_14.setObjectName("overwrite_le_14")
        self.time_series_translator_grid.addWidget(self.overwrite_le_14, 13, 0, 1, 1)
        self.overwrite_le_15 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_15.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_15.setReadOnly(True)
        self.overwrite_le_15.setObjectName("overwrite_le_15")
        self.time_series_translator_grid.addWidget(self.overwrite_le_15, 14, 0, 1, 1)
        self.overwrite_le_16 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_16.setReadOnly(True)
        self.overwrite_le_16.setObjectName("overwrite_le_16")
        self.time_series_translator_grid.addWidget(self.overwrite_le_16, 15, 0, 1, 1)
        self.overwrite_le_17 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_17.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_17.setReadOnly(True)
        self.overwrite_le_17.setObjectName("overwrite_le_17")
        self.time_series_translator_grid.addWidget(self.overwrite_le_17, 16, 0, 1, 1)
        self.overwrite_le_18 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_18.setReadOnly(True)
        self.overwrite_le_18.setObjectName("overwrite_le_18")
        self.time_series_translator_grid.addWidget(self.overwrite_le_18, 17, 0, 1, 1)
        self.overwrite_le_19 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_19.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_19.setReadOnly(True)
        self.overwrite_le_19.setObjectName("overwrite_le_19")
        self.time_series_translator_grid.addWidget(self.overwrite_le_19, 18, 0, 1, 1)
        self.overwrite_le_20 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_20.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_20.setReadOnly(True)
        self.overwrite_le_20.setObjectName("overwrite_le_20")
        self.time_series_translator_grid.addWidget(self.overwrite_le_20, 19, 0, 1, 1)
        self.overwrite_le_21 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_21.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_21.setReadOnly(True)
        self.overwrite_le_21.setObjectName("overwrite_le_21")
        self.time_series_translator_grid.addWidget(self.overwrite_le_21, 20, 0, 1, 1)
        self.overwrite_le_22 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_22.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_22.setReadOnly(True)
        self.overwrite_le_22.setObjectName("overwrite_le_22")
        self.time_series_translator_grid.addWidget(self.overwrite_le_22, 21, 0, 1, 1)
        self.overwrite_le_23 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_23.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_23.setReadOnly(True)
        self.overwrite_le_23.setObjectName("overwrite_le_23")
        self.time_series_translator_grid.addWidget(self.overwrite_le_23, 22, 0, 1, 1)
        self.overwrite_le_24 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_24.setReadOnly(True)
        self.overwrite_le_24.setObjectName("overwrite_le_24")
        self.time_series_translator_grid.addWidget(self.overwrite_le_24, 23, 0, 1, 1)
        self.overwrite_le_25 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.overwrite_le_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.overwrite_le_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.overwrite_le_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.overwrite_le_25.setReadOnly(True)
        self.overwrite_le_25.setObjectName("overwrite_le_25")
        self.time_series_translator_grid.addWidget(self.overwrite_le_25, 24, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.time_series_translator_gb)
        self.pushButton.setGeometry(QtCore.QRect(770, 1280, 150, 30))
        self.pushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(1100, 50, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.time_series_translator_gb.setTitle(_translate("Dialog", "Select Timeseries Type:"))
        self.overwrite_line_cb_14.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_14.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_14.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_14.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_18.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_18.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_18.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_18.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_17.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_17.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_17.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_17.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_15.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_15.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_15.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_15.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_16.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_16.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_16.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_16.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_21.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_21.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_21.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_21.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_19.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_19.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_19.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_19.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_22.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_22.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_22.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_22.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_20.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_20.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_20.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_20.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_10.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_10.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_10.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_10.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_8.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_8.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_8.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_8.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_11.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_11.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_11.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_11.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_9.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_9.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_9.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_9.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_12.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_12.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_12.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_12.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_13.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_13.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_13.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_13.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_24.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_24.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_24.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_24.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_25.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_25.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_25.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_25.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_23.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_23.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_23.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_23.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_1.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_1.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_1.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_1.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_3.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_3.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_3.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_3.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_2.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_2.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_2.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_2.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_4.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_4.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_4.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_4.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_6.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_6.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_6.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_6.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_5.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_5.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_5.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_5.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.overwrite_line_cb_7.setItemText(0, _translate("Dialog", "Electric Field Potential Timeseries"))
        self.overwrite_line_cb_7.setItemText(1, _translate("Dialog", "Alignment Timeseries"))
        self.overwrite_line_cb_7.setItemText(2, _translate("Dialog", "Stimulus Timeseries"))
        self.overwrite_line_cb_7.setItemText(3, _translate("Dialog", "Other Timeseries Data"))
        self.pushButton.setText(_translate("Dialog", "Update/Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

